/**
 * Fixed, realistic comment-style sentences for latency benchmarks. Lengths
 * mirror film and TV discussion threads: mostly short, some long. The plot
 * details are invented so the benchmark itself spoils nothing.
 */
export const BENCH_SENTENCES: string[] = [
  'Just finished episode four and I need to talk about it.',
  'The cinematography in the forest chase was unreal.',
  'No way the captain was working for the other side the whole time.',
  'Anyone else think the soundtrack carried the slower middle episodes?',
  'I did not see that ending coming at all.',
  'She survives the fire, which makes the final scene hit so much harder.',
  'Rewatching season one before the new one drops next week.',
  'The twist is that the narrator has been dead since the first episode.',
  'Honestly the pacing dragged a bit around episode six.',
  'Can we appreciate how good the supporting cast is this season?',
  'When the brother turns up alive in the last minute I screamed.',
  'This show keeps getting better every week.',
  'I love how the opening credits change slightly each episode.',
  'The mentor betrays them in the finale and it recontextualises everything.',
  'Is it worth starting if I only have time for one episode a week?',
  'Their chemistry is the best part of the whole series.',
  'The villain was her father all along, and the clues were there from the start.',
  'Mild complaint, but the subtitles were out of sync on my stream.',
  'I think the director said in an interview that the ending was always planned.',
  'Two main characters die in the penultimate episode.',
  'That long single take in the hallway must have taken days to shoot.',
  'Book readers, please keep quiet about what happens next.',
  'The heist fails and they all end up in prison by the last scene.',
  'Please tell me there is a second season.',
  'The dog makes it to the end, for anyone worried.',
  'Every frame of the desert sequence could be a painting.',
  'Turns out the whole town was part of the experiment.',
  'I was not expecting to cry at a show about office workers.',
  'The wedding gets interrupted when the ex shows up with the evidence.',
  'The score by the new composer is fantastic, especially the main theme.',
  'After the time jump they are both working for the company they fought against.',
  'Watching this with subtitles on made me catch so many small details.',
  'Honestly one of the best pilots I have seen in years, the writing is sharp.',
  'The detective figures out it was the neighbour by the midpoint of the finale.',
  'It is slow at first but stick with it past the third episode.',
  'The final shot mirrors the first one, which is a lovely touch.',
  'Why does everyone in this show whisper all the time?',
  'The king is killed at the feast and his youngest daughter takes the throne.',
  'Loved the callback to the first season in the diner scene.',
  'The AI was controlling the ship from the very beginning.',
  'Great acting, messy plot, would still recommend.',
  'He loses his memory again in the last episode, so we are back to square one.',
  'Does anyone know where they filmed the lighthouse scenes?',
  'By the end she chooses to stay behind and close the portal herself.',
  'The costumes alone deserve an award.',
  'It was a dream the entire time, which honestly felt like a cheat.',
  'Cannot believe we have to wait a whole year for the next part.',
  'The twins were swapped at birth and that is why the inheritance goes to him.',
];
